apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.apiextensions.core.oam.dev
  labels:
    api: kuebvela-vela-prism
    apiserver: "true"
    {{- include "vela-prism.labels" . | nindent 4 }}
spec:
  version: v1alpha1
  group: apiextensions.core.oam.dev
  groupPriorityMinimum: 2000
  service:
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    port: {{ .Values.port }}
  versionPriority: 10
  insecureSkipTLSVerify: {{ not .Values.secureTLS.enabled }}
  {{ if .Values.secureTLS.enabled }}
  caBundle: Cg==
  {{ end }}