apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vela-prism.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "vela-prism.labels" . | nindent 4 }}
    {{- include "vela-prism.selector-labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}